version: '3.8'

services:
  postgress:
    image: postgres:17
    container_name: postgres_db
  environment:
    POSTGRES: aryansyah
    POSTGRES_PASSWORD: ary12345
    POSTGRES_DB: school
  ports:
    - '5432:5432'
  volumes:
    - 'postgres_data:/var/lib/postgresql/data'
  
  app: 
    container_name: next-dashboard
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL:postgresql://aryansyah:ary12345@localhost:5432/school
    depends_on:
      - postgres